apiVersion: v1
kind: Template
metadata:
  name: olm-artifacts-template

parameters:
- name: REGISTRY_IMG
  required: true
- name: CHANNEL
  value: staging
- name: IMAGE_TAG
  value: latest
- name: ACCOUNT_LIMIT
  required: true
- name: ROOT_OU_ID
  required: true
- name: BASE_OU_ID
  required: true

objects:
- apiVersion: operators.coreos.com/v1alpha1
  kind: CatalogSource
  metadata:
    name: aws-account-operator-catalog
  spec:
    sourceType: grpc
    image: ${REGISTRY_IMG}:${CHANNEL}-${IMAGE_TAG}
    displayName: aws-account-operator Registry
    publisher: SRE 

- apiVersion: operators.coreos.com/v1alpha2
  kind: OperatorGroup
  metadata:
    name: aws-account-operator-og
  spec:
    targetNamespaces:
    - aws-account-operator

- apiVersion: operators.coreos.com/v1alpha1
  kind: Subscription
  metadata:
    name: aws-account-operator
  spec:
    channel: ${CHANNEL}
    name: aws-account-operator
    source: aws-account-operator-catalog
    sourceNamespace: aws-account-operator

- apiVersion: v1
  kind: ConfigMap
  metadata:
    name: aws-account-operator-configmap
    namespace: aws-account-operator
  data:
    account-limit: "${ACCOUNT_LIMIT}"
    root: ${ROOT_OU_ID}
    base: ${BASE_OU_ID}
