apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: awsfederatedroles.aws.managed.openshift.io
spec:
  group: aws.managed.openshift.io
  names:
    kind: AWSFederatedRole
    listKind: AWSFederatedRoleList
    plural: awsfederatedroles
    singular: awsfederatedrole
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            awsCustomPolicy:
              description: AWSCustomPolicy is the defenition of a custom aws permission
                policy that will be associated with this role
              properties:
                awsStatements:
                  items:
                    properties:
                      action:
                        items:
                          type: string
                        type: array
                      effect:
                        type: string
                      principal:
                        properties:
                          AWS:
                            description: aws account id
                            type: string
                        required:
                        - AWS
                        type: object
                      resourcce:
                        items:
                          type: string
                        type: array
                    required:
                    - effect
                    - action
                    type: object
                  type: array
                description:
                  type: string
                name:
                  type: string
              required:
              - name
              - description
              - awsStatements
              type: object
            awsManagedPolicies:
              description: AWSManagedPolicies is a list of amazong managed policies
                that exist in aws
              items:
                type: string
              type: array
            roleDescription:
              type: string
          required:
          - roleDescription
          type: object
        status:
          properties:
            state:
              type: string
          required:
          - state
          type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
