apiVersion: aws.managed.openshift.io/v1alpha1
kind: AWSFederatedRole
metadata:
  name: customer-admin
spec:
  roleDescription: This is the description of customer-admin
  # Custom policy definition 
  awsCustomPolicy:
    name:  CustomerAdministratorAccess
    description: Description of CustomerAdministratorAccess
    # list of statements for the policy
    awsStatements:
      - effect: Allow
        action:
          - "ec2:AttachVpnGateway"
          - "ec2:DescribeVpnConnections"
          - "ec2:AcceptVpcPeeringConnection"
          - "ec2:DeleteVpcPeeringConnection"
          - "ec2:DescribeVpcPeeringConnections"
          - "ec2:CreateVpnConnectionRoute"
          - "ec2:RejectVpcPeeringConnection"
          - "ec2:DetachVpnGateway"
          - "ec2:DeleteVpnConnectionRoute"
          - "ec2:DeleteVpnGateway"
          - "ec2:DescribeVpcs"
          - "ec2:CreateVpnGateway"
          - "ec2:ModifyVpcPeeringConnectionOptions"
          - "ec2:DeleteVpnConnection"
          - "ec2:CreateVpcPeeringConnection"
          - "ec2:DescribeVpnGateways"
          - "ec2:CreateVpnConnection"
          - "ec2:DescribeRouteTables"
          - "ec2:CreateTags"
          - "ec2:CreateRoute"
          - "support:*"
          - "directconnect:*"
        resource: 
          - "*"
  # list of  AWS managed
  awsManagedPolicies:
    - "AWSAccountUsageReportAccess"
    - "AmazonEC2ReadOnlyAccess"
    - "AmazonS3ReadOnlyAccess"
    - "IAMReadOnlyAccess"
    - "BillingReadOnlyAccess"