apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: awsfederatedroles.aws.managed.openshift.io
spec:
  additionalPrinterColumns:
  - JSONPath: .status.state
    description: Status the federated role
    name: State
    type: string
  - JSONPath: .metadata.creationTimestamp
    description: Age since federated role was created
    name: Age
    type: date
  group: aws.managed.openshift.io
  names:
    kind: AWSFederatedRole
    listKind: AWSFederatedRoleList
    plural: awsfederatedroles
    singular: awsfederatedrole
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            awsCustomPolicy:
              description: AWSCustomPolicy is the defenition of a custom aws permission
                policy that will be associated with this role
              properties:
                awsStatements:
                  items:
                    properties:
                      action:
                        items:
                          type: string
                        type: array
                      effect:
                        type: string
                      principal:
                        properties:
                          AWS:
                            description: aws account id
                            type: string
                        required:
                        - AWS
                        type: object
                      resource:
                        items:
                          type: string
                        type: array
                    required:
                    - effect
                    - action
                    type: object
                  type: array
                description:
                  type: string
                name:
                  type: string
              required:
              - name
              - description
              - awsStatements
              type: object
            awsManagedPolicies:
              description: AWSManagedPolicies is a list of amazong managed policies
                that exist in aws
              items:
                type: string
              type: array
            roleDescription:
              description: RoleDescription is a user friendly description of the role,
                this discription will be displayed in the OCM user interface
              type: string
            roleDisplayName:
              description: RoleDisplayName is a user friendly display name for the
                OCM user interface
              type: string
          required:
          - roleDisplayName
          - roleDescription
          type: object
        status:
          properties:
            conditions:
              items:
                properties:
                  lastProbeTime:
                    description: LastProbeTime is the last time we probed the condition.
                    format: date-time
                    type: string
                  lastTransitionTime:
                    description: LastTransitionTime is the laste time the condition
                      transitioned from one status to another.
                    format: date-time
                    type: string
                  message:
                    description: Message is a human-readable message indicating details
                      about last transition.
                    type: string
                  reason:
                    description: Reason is a unique, one-word, CamelCase reason for
                      the condition's last transition.
                    type: string
                  status:
                    description: Status is the status of the condition
                    type: string
                  type:
                    description: Type is the type of the condition.
                    type: string
                required:
                - type
                - status
                type: object
              type: array
            state:
              type: string
          required:
          - state
          - conditions
          type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
