apiVersion: aws.managed.openshift.io/v1alpha1
kind: AWSFederatedAccountAccess
metadata:
  name: clustername.customeraccountname.rolename
spec:
  customerAccountID: CustomerAccountID
  awsCredentialSecret:
    name: secretName
    namespace: secretNamespace
  awsFederatedRoleName: RoleName