apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  name: accountclaims.aws.managed.openshift.io
spec:
  group: aws.managed.openshift.io
  names:
    kind: AccountClaim
    listKind: AccountClaimList
    plural: accountclaims
    singular: accountclaim
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          type: object
        status:
          type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
