apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  name: accountpools.aws.managed.openshift.io
spec:
  additionalPrinterColumns:
  - JSONPath: .status.poolsize
    name: Pool Size
    type: integer
  - JSONPath: .status.unclaimedaccounts
    name: Unclaimed Accounts
    type: integer
  - JSONPath: .status.claimedaccounts
    name: Claimed Accounts
    type: integer
  group: aws.managed.openshift.io
  names:
    kind: AccountPool
    listKind: AccountPoolList
    plural: accountpools
    singular: accountpool
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          type: object
        status:
          type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
