apiVersion: aws.managed.openshift.io/v1alpha1
kind: AWSFederatedAccountAccess
metadata:
  name: test-account-access 
  namespace: aws-account-operator
spec:
  awsCustomerCredentialSecret: 
    name: osd-creds-mgmt-w2tclb-secret
    namespace: aws-account-operator
  externalCustomerAWSIAMARN: arn:aws:iam::414830704956:user/james.harrington
  awsFederatedRoleName: read-only 
